# Generated by Django 3.0.8 on 2020-07-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('descricao', models.TextField(default='BRL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('ultimaCotacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotação')),
                ('peso', models.IntegerField(verbose_name='Peso')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valorTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('percIdeal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='% Ideal')),
                ('percPosse', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='% Posse')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoriaAtivo', verbose_name='Categoria')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Moeda', verbose_name='Moeda')),
            ],
            options={
                'verbose_name_plural': 'Acoes',
            },
        ),
        migrations.AlterField(
            model_name='categoriaativo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoAtivo', verbose_name='Tipo Ativo'),
        ),
    ]
