# Generated by Django 3.0.8 on 2020-07-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200719_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='moeda',
            name='dataUltimaCotacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moeda',
            name='ultimaCotacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotação'),
        ),
        migrations.AlterField(
            model_name='categoriaativo',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
